server:
  log_level: info

metrics:
  global:
    scrape_interval: 15s
  configs:
    - name: stock_monitoring
      scrape_configs:
        - job_name: 'prometheus'
          static_configs:
            - targets: ['prometheus:9090']
        - job_name: 'stock_exporter'   
          static_configs:
            - targets: ['stock_exporter:8000']
      remote_write:
        - url: https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom/push
          basic_auth:
            username: 
            password: